name: Trigger Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/peter-evans/repository-dispatch
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: FPVirtual/Nueva_Documentacion
          event-type: docs-updated